name: Test

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy to Heroku
          env:
            HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
            HEROKU_APP_NAME: "your-app-name-here"
          if: github.ref == 'refs/heads/master' && job.status == 'success'
          run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$heroku-vue-meetup-app.git origin/master:master  
        
   
