name: Test

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
              id: heroku
              with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: "YOUR APP's NAME" #Must be unique in Heroku
                heroku_email: "YOUR EMAIL"
